image: maven:3.9-eclipse-temurin-21

matrix:
  - env: SCRIPT=test

install:
  - mvn dependency:go-offline

script:
  - if [ "$SCRIPT" = "test" ]; then mvn clean package; fi

cache:
  - .m2/repository
